In [1]:
from library.optimiser import *
from library.objective_function import *
from library.post_analysis import *
from library.experiments import *
%matplotlib inline
SEED = 23191

In [6]:
tak = tuned_ackley(dim=5)
ad = adam()
x0 = np.array([12.34232, 3.3412, 2.23, 3.3, 3.2])
optmizerParas = {'x0': x0,
         'alpha': 0.01,
         'beta_1': 0.9, 
         'beta_2': 0.999, 
         'epsilon': 1e-8, 
         'max_iter': 1000,
         'tol': 1e-5,              
         'verbose': True,
         'record': False}
ad.set_parameters(optmizerParas)
ad.optimise(tak)



*******starting optimisation from intitial point:  [12.34232  3.3412   2.23     3.3      3.2    ]


(array([-0.00191471, -0.00481628, -0.00223462, -0.00172887, -0.00010251]),
 0.010558381933893912,
 {'status': None, 'evals': 1000})

In [8]:
ak = ackley()
ls = line_search(dim=6)
x0 = np.array([12.34232, 34.3412, 34.3, 23.3434, 343.212, 232.122])
optmizerParas = {'x0': x0,
         'alpha': 1,
         'beta': 0.1, 
         'max_iter': 1000,
         'tol': 1e-5,              
         'verbose': True,
         'record': False}
ls.set_parameters(optmizerParas)
ls.optimise(ak)


*******starting optimisation from intitial point:  [ 12.34232  34.3412   34.3      23.3434  343.212   232.122  ]


(array([ 11.99999998,  33.99999999,  34.        ,  22.99999998,
        343.00000002, 232.00000002]),
 19.999999999999968,
 {'status': None, 'evals': 29})

In [10]:
ak = ackley()
x0_2 = np.array([12.34232, 34.3412, 23.22, 4.223333332, 3.12021, 223.343, 34.343])
dim = x0_2.shape[0]
cma = cma_es(dim=dim)
paras = {'x0': x0_2,
         'std': np.ones((dim,)) * 3, 
         'tol': 1e-5, 
         'adjust_func': line_search(), 
         'record': False, 
         'verbose': True}
cma.set_parameters(paras)
cma.optimise(ak)



*******starting optimisation from intitial mean:  [ 12.34232     34.3412      23.22         4.22333333   3.12021
 223.343       34.343     ]
eigenvalue of variance = [6.54606319 4.06381807 2.15481538 3.55028104 2.71468067 2.98968522
 3.27417869]
total iterations = 96, total evaluatios = 36487
found minimum position = [-1.01437493e-16  3.61992097e-18  1.52166618e-16  4.53131041e-17
 -7.77591494e-18  1.09635175e-16 -1.47933186e-16], found minimum = 4.440892098500626e-16


(array([-1.01437493e-16,  3.61992097e-18,  1.52166618e-16,  4.53131041e-17,
        -7.77591494e-18,  1.09635175e-16, -1.47933186e-16]),
 4.440892098500626e-16,
 {'val': [],
  'arg': [],
  'x_adjust': [],
  'evals_per_iter': [],
  'mean': [],
  'std': [],
  'status': None,
  'evals': 36487})