In [27]:
import time
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import os

In [30]:
PATH

'/Users/huajian/Downloads/MinimalDeepSDF/example1/Optimizations/750/Codes/3.pth'

In [29]:
os.path.dirname(PATH)

'/Users/huajian/Downloads/MinimalDeepSDF/example1/Optimizations/750/Codes'

In [6]:
# Define model
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize model
model = TheModelClass()

# Initialize optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

# Print model's state_dict
print("Model's state_dict:")
for param_tensor in model.state_dict():
    print(param_tensor, "\t", model.state_dict()[param_tensor].size())

# Print optimizer's state_dict
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
conv1.weight 	 torch.Size([6, 3, 5, 5])
conv1.bias 	 torch.Size([6])
conv2.weight 	 torch.Size([16, 6, 5, 5])
conv2.bias 	 torch.Size([16])
fc1.weight 	 torch.Size([120, 400])
fc1.bias 	 torch.Size([120])
fc2.weight 	 torch.Size([84, 120])
fc2.bias 	 torch.Size([84])
fc3.weight 	 torch.Size([10, 84])
fc3.bias 	 torch.Size([10])
Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [4814476144, 4814476304, 4599200656, 4814476224, 4814476384, 4814476464, 4814476544, 4814476624, 4814476704, 4814476784]}]


In [15]:
np.array(model.state_dict()['conv1.weight'][0,1,2,2])

array(0.01352374, dtype=float32)

In [24]:
PATH = "/Users/huajian/Downloads/MinimalDeepSDF/example1/Optimizations/750/Codes/"

In [25]:
mesh3 = torch.load(PATH)

In [23]:
mesh399

tensor([[[-0.1588, -0.3376,  0.0932, -0.0402,  0.1580,  0.2382, -0.0432,
          -0.0909]]], requires_grad=True)

In [54]:
mesh3.unsqueeze(-1).shape

torch.Size([1, 1, 8, 1])

In [63]:
mesh3.repeat(1,1,2)

tensor([[[-0.3172, -0.4519, -0.1284, -0.0009,  0.1246,  0.3083, -0.1360,
          -0.0999, -0.3172, -0.4519, -0.1284, -0.0009,  0.1246,  0.3083,
          -0.1360, -0.0999]]], grad_fn=<RepeatBackward>)

In [75]:
mesh3.transpose(1,0)

tensor([[[-0.3172, -0.4519, -0.1284, -0.0009,  0.1246,  0.3083, -0.1360,
          -0.0999]]], grad_fn=<TransposeBackward0>)

In [77]:
mesh3.transpose(0,2)

tensor([[[-0.3172]],

        [[-0.4519]],

        [[-0.1284]],

        [[-0.0009]],

        [[ 0.1246]],

        [[ 0.3083]],

        [[-0.1360]],

        [[-0.0999]]], grad_fn=<TransposeBackward0>)